config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :minions

  # get "search", to: "minions#search"
  resources :users, only: [:show]
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :minion

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/minion.rb
class Minion < ApplicationRecord
  belongs_to :user
  has_many :users, through: :bookings
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :price_per_day, presence: true
  validates :price_per_day, numericality: true
  validates :name, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name_and_skills,
    against: [ :name, :skills ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :minions, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, only: %i[new]
  include Pundit::Authorization

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def configure_permitted_parameters
    # devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show update]
  before_action :authenticate_user!, only: %i[index show create]
  def index
    @bookings = policy_scope(Booking.where("user_id = #{current_user.id}").order(created_at: :asc))

    @owned_minions = policy_scope(Minion.where("user_id = #{current_user.id}"))

    @hosted_bookings = @owned_minions.map do |owned_minion|
      Booking.where("minion_id = #{owned_minion.id}")
    end
    @hosted_bookings.flatten!
    # bookings containing a minion which you (the user) host
    # find bookings where
  end

  def show
    authorize @booking
  end

  def new
    @booking = Booking.new
    authorize @booking
  end

  def create
    minion = Minion.find(params[:booking][:minion_id])
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    @booking.minion = minion
    if @booking.save!
      redirect_to bookings_path
    else
      render :new
    end
    authorize @booking
  end

  def update
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
    authorize @booking
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :user_id, :minion_id, :status)
  end
end

app/controllers/minion_controller.rb
class MinionController < ApplicationController
  # before_action :set_minion, only: [:edit, :show]
  def index
    @minions = Minion.all
  end

  def create
    @minion = Minion.new(minion_params)
    if @minion.save
      redirect_to minions_path
    # else
      # render :new
    end
  end

  private

  def set_minion
    @minion = Minion.find(params[:id])
  end

  def minion_params
    params.require(:minion).permit(:name, :skills)
  end
end

app/controllers/minions_controller.rb
class MinionsController < ApplicationController
  before_action :set_minion, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[edit update create]

  def index
    if params[:query].present?
      @minions = policy_scope(Minion.search_by_name_and_skills(params[:query])).order(created_at: :asc)
    else
      @minions = policy_scope(Minion).order(created_at: :asc)
    end
    @markers = @minions.geocoded.map do |minion|
      {
        lat: minion.latitude,
        lng: minion.longitude,
        info_window: render_to_string(partial: "info_window", locals: { minion: minion }),
        image_url: helpers.asset_url("minion.png")
      }
    end
  end

  def create
    @minion = Minion.new(minion_params)
    @minion.user_id = current_user.id
    if @minion.save
      redirect_to minions_path
    else
      render :new
    end
    authorize @minion
  end

  def show
    @booking = Booking.new
    authorize @minion
    authorize @booking
  end

  def update
    # raise
    if @minion.update!(minion_params)
      redirect_to minion_path(@minion)
    else
      render :edit
    end
    authorize @minion
  end

  def edit
    authorize @minion
  end

  def destroy
    @minion.destroy
    redirect_to minions_path
    authorize @minion
  end

  def new
    @minion = Minion.new
    authorize @minion
  end

  private

  def set_minion
    @minion = Minion.find(params[:id])
  end

  def minion_params
    params.require(:minion).permit(:name, :description, :skills, :price_per_day, :user_id, :photo, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @minions = Minion.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show]

  def show
    @owned_minions = policy_scope(Minion.where("user_id = #{current_user.id}"))
    @user = current_user
    authorize @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container my-3">
  <h1 class="container-header">My Bookings</h1>
  <div class="card-container">
  <% if Booking.count == 0 %>
      <p>You have no booking yet!</p>
      <%= link_to 'Find a minion now', minions_path, class: 'btn-blue ' %>
  <% else %>
    <% @bookings.each do |booking| %>
      <% if policy(Booking).show? %>
          <div class="card-product">
            <%= cl_image_tag booking.minion.photo.key, height: 300, width: 400, crop: :fill %>
            <%= link_to booking_path(booking) do %>
            <div class="card-product-infos">
              <h2>Minion: <%= booking.minion.name %></h2>
              <p>Date: <%= booking.start_date %> - <%= booking.end_date%></p>
            </div>
            <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  </div>
  <br>
  <br>
  <h1 class="container-header mt-5">My Minions' bookings</h1>
  <div class="card-container mb-5">
    <% if Booking.count == 0 %>
      <p>You have no booking yet!</p>
      <%= link_to 'Host your minion now', new_minion_path, class: 'btn-blue' %>
    <% else %>
        <% @hosted_bookings.each do |booking| %>
          <% if policy(Booking).show? %>
              <div class="card-product">
                <%= cl_image_tag booking.minion.photo.key, height: 300, width: 400, crop: :fill %>
                <%= link_to booking_path(booking) do %>
                <div class="card-product-infos">
                  <h2>Minion: <%= booking.minion.name %></h2>
                  <p>Date: <%= booking.start_date %> - <%= booking.end_date%></p>
                </div>
                <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
</div>

app/views/bookings/show.html.erb
<div class="booking-container">
  <div class="row">
    <div class="col-8">
      <% if @booking.minion.user_id == current_user.id && @booking.status === 'pending' %>
        <h1>Booking request for <b><%= @booking.minion.name %></b></h1>
        <br>
        <p>Status: <b><%= @booking.status %></b></p>
        <p>Requested by: <b><%= @booking.user.username %></b></p>
        <p>Start date: <b><%= @booking.start_date %></b></p>
        <p>End date: <b><%= @booking.end_date %></b></p>
        <div class="decline-accept-booking">
          <%= simple_form_for @booking do  |t| %>
            <%= t.input :status, input_html: {value: 'Decline', class: 'd-none'}, label: false %>
            <%= t.submit "Decline", class: "btn btn-red" %>
          <% end %>
          <%= simple_form_for @booking do  |t| %>
            <%= t.input :status, input_html: {value: 'Accept', class: 'd-none'}, label: false %>
            <%= t.submit "Accept", class: "btn btn-blue" %>
          <% end %>
        </div>
      <% else %>
        <h1>Your booking request for <b><%= @booking.minion.name %></b></h1>
        <br>
        <p>Status: <b><%= @booking.status %></b></p>
        <p>Owner: <b><%= @booking.minion.user.username %></b></p>
        <p>Start date: <b><%= @booking.start_date %></b></p>
        <p>End date: <b><%= @booking.end_date %></b></p>
      <% end %>
    </div>
    <div class="col-4">
      <div class="image-container">
        <%= cl_image_tag @booking.minion.photo.key, height: 300, width: 250, crop: :fill %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirMinions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/d29be27bb4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>


  </head>

  <body style="position:relative" data-no-turbolink="true">
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "shared/footer-margin" %>
    <%= render "shared/footer" %>
  </body>

</html>

app/views/minions/_info_window.html.erb
<h2><%= link_to minion.name, minion_path(minion) %></h2>
<p><%= minion.address %></p>

app/views/minions/edit.html.erb
<div class="container" style="margin-bottom:30px">
<h1>Edit <%= @minion.name %></h1>
<div class="form-inputs">
  <%= simple_form_for @minion, data: { turbolinks: false } do |f| %>
    <%= f.input :name, required: true, autofocus: true %>
    <%= f.input :description, required: false %>
    <%= f.input :skills, required: false %>
    <%= f.input :price_per_day, required: true%>
    <%= f.input :address, required: false%>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "Update" %>
  </div>
  <% end %>
</div>

app/views/minions/index.html.erb
<div class='container'>
  <div class="row">
    <div class="col-6">
     <div class="nav-filter">
      <p><strong>+ <%= Minion.count %> Minions for you</strong></p>
      <%# <button type="button" class="btn btn-white" data-toggle="modal" data-target="#exampleModal">
          Filter <i class="fa-solid fa-sliders"></i> #placeholder
      </button> %>
     </div>
     <div class="card-container-index my-3">
        <% @minions.each do |minion| %>
          <% if policy(Minion).show? %>
          <div class="card">
              <% if minion.photo.attached?  %>
                <%= cl_image_tag minion.photo.key, height: 300, width: 250, crop: :fill, class: "card-image" %>
               <% else %>
                <img src='https://i.pinimg.com/736x/95/a1/95/95a195e665368324f79aeb0904e95d6d--happy-valentines-day-minions-quotes.jpg'  alt="">
               <% end %>
              <div class="card_text-container">
                <div class="d-flex justify-content-between">
                  <p><strong><%= minion.name %></strong></p>
                  <p><i class="fa-solid fa-star"></i> 5.0</p>
                </div>
                <p>Skills: <%= minion.skills %></p>
                <p>17km away</p>
                <p><strong>€ <%= minion.price_per_day %></strong></p>
              </div>
              <%= link_to 'Find out more', minion_path(minion), class: 'btn btn-blue' %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-6">
      <div style="width: 100%; height: 600px;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
</div>

app/views/minions/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-6">
      <h1>Host your minion</h1>
      <p>Hello <strong><%= current_user.username %></strong>! </p>
      <%= simple_form_for @minion do  |t| %>
        <%= t.input :name %>
        <%= t.input :description %>
        <%= t.input :skills %>
        <%= t.input :price_per_day %>
        <%= t.input :photo, as: :file %>
        <%= t.input :address,
                    input_html: { data: { geocoder_target: "address" }, class: "d-none" },
                    wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
        <%= t.submit "Create a minion", class: 'btn btn-primary' %>
      <% end %>
      <br>
      <br>
      <br>
      <br>
    </div>
  </div>
</div>

app/views/minions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <h1>Hello from <b><%=@minion.name %></b>!</h1>
      <p><i class="fa-solid fa-star"></i> <span>(5.0) Review</span> - Skills: <b><%= @minion.skills %></b></p>
      <p>Owner: <b><%= @minion.user.username %></b></p>
      <div class="edit-and-delete">
        <% if current_user != nil %>
          <% if @minion.user_id === current_user.id %>
            <%= link_to 'Edit', edit_minion_path, class: 'btn-blue'%>
            <%= link_to 'Delete', minion_path(@minion), method: :delete, class: 'btn-red'%>
          <% end %>
        <% end %>
      </div>
    </div>
      <div class="col-7">
        <div class="horizontal-img-flex">
           <%= cl_image_tag("#{@minion.photo.key}", width: 300, height: 300) %>
        </div>
      </div>
  </div>
  <div class="row">
    <div class="col-8">
      <h2>Know more about <b><%= @minion.name %></b>!</h2>
      <% if @minion.description.nil? && @minion.user_id != current_user.id %>
        <p>The owner has not added a description for this minion yet.</p>
      <% elsif @minion.description.nil? %>
        <p>Your minion doesnt have a description yet. To add one you can edit the minion.</p>
      <% else %>
        <p><%= @minion.description %></p>
      <% end %>
    </div>
    <div class="col-4">
      <%= simple_form_for @booking do  |t| %>
        <%= t.input :minion_id, :as => :hidden, :input_html => { :value => @minion.id } %>
        <%= t.input :start_date, as: :date %>
        <%= t.input :end_date, as: :date%>
        <%= t.submit "Book now", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class='my-2'>
  <div class="banner">
    <div class="banner_container">
      <h1><strong>Uh, la cucaracha?</strong></h1>
      <p>Browse through millions of Minions and find your perfect match.</p>
      <%= link_to 'Discover all minions', minions_path, class: 'btn-blue' %>
      <img src="https://www.pngmart.com/files/12/Group-Minions-PNG-Photo.png" alt="minions">
    </div>
  </div>
  <div class="container">
  <h2>Explore the best Minions</h2>
  <div class="container card-container">
      <% @minions.take(3).each do |minion| %>
        <div class="card">
          <%= cl_image_tag("#{minion.photo.key}",
                            width: 250, height: 300, crop: :fill, class: "card-image") %>
          <div class="card_text-container">
            <div class="d-flex justify-content-between">
              <p><strong><%= minion.name %></strong></p>
              <p><i class="fa-solid fa-star"></i> 5.0</p>
            </div>
            <p>Skills: <%= minion.skills %></p>
            <p>17km away</p>
            <p><strong>€ <%= minion.price_per_day %></strong></p>
          </div>
          <%= link_to 'Find out more', minion_path(minion), class: 'btn btn-blue' %>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_footer-margin.html.erb
<div class="footer-margin">
<p></p>
</div>

app/views/shared/_footer.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

<div class="footer-container">
  <%= render "shared/logo" %>
  <div class="socials">
    <a href="#"><i class="fa-brands fa-instagram"></i></a>
    <a href="#"><i class="fa-brands fa-twitter"></i></a>
    <a href="#"><i class="fa-brands fa-youtube"></i></a>
    <a href="#"><i class="fa-brands fa-square-facebook"></i></a>
  </div>
</div>

app/views/shared/_logo.html.erb
<span class="icon_minion_flex">
  <%= image_tag "minion.png", width: 40 %>
  <span><%= link_to 'AirMinions', root_path , class: 'logo'  %></span>
</span>

app/views/shared/_navbar.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">

<div class="container">
  <nav>
    <ul>
      <li>
        <%= render "shared/logo" %>
      </li>
      <li>
      <form action="/minions" class="form_flex">
        <input class='search_input' name="query" type="text" placeholder='what are you looking for?'>
        <button><i class="fas fa-search"></i></button>
      </form>
      </li>
      <% if user_signed_in? %>
        <li style="width: 150px">
          <div class="dropdown">
            <button class="btn btn-outline-primary dropdown-toggle border-round" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= image_tag "https://kitt.lewagon.com/placeholder/users/random", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            </button>
            <ul class="dropdown-menu dropdown-menu-dark">
              <li><%= link_to "Host a minion", new_minion_path, class: "dropdown-item" %></li>
              <li><%= link_to "My Bookings", bookings_path, class: "dropdown-item"%></li>
              <li><%= link_to "My Profile", user_path(current_user.id), class: "dropdown-item"%></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item"%></li>
            </ul>
          </div>
        </li>
    </ul>
      <% else %>
      <li><%= link_to "sign in", new_user_session_path %> or <%= link_to "sign up", new_user_registration_path %></li>
      <% end %>
  </nav>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <h1>Hello <strong><%= current_user.username %></strong>!</h1>
  <br>
  <br>
  <p>Email: <%= current_user.email %></p>
  <p>Full name: <%= current_user.first_name %> <%= current_user.last_name %></p>
  <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'btn-blue'%>
  <%= link_to 'My bookings', bookings_path, class: 'btn-blue'%>
    <div>
    <h3>My minions:</h3>

  <% if @owned_minions.empty? %>
    <p>You don't have any minions</p>
    <%= link_to 'Host a minion', new_minion_path, class: 'btn-blue' %>
  <% else %>
    <div class="card-container-my-minions">
          <% @owned_minions.each do |minion| %>
            <% if policy(Minion).show? %>
                <div class="card-product">
                  <%= cl_image_tag minion.photo.key, height: 300, width: 400, crop: :fill %>
                  <%= link_to minion_path(minion) do %>
                  <div class="card-product-infos">
                    <h2>Minion: <%= minion.name %></h2>
                    <p>Skills: <%= minion.skills %></p>
                  </div>
                  <% end %>
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  <% end %>
</div>